[supervisord]
nodaemon=true


[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


[program:fras]
command=/opt/venv-fras/bin/python -m uvicorn main:app --host 127.0.0.1 --port 7861
directory=/app/facial-recognition-attendance-system/backend
environment=PYTHONPATH="/app/facial-recognition-attendance-system/backend/"
autostart=true
autorestart=false
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


[program:ai-web-vuln]
command=/opt/venv-ai-vuln/bin/python -m uvicorn main:app --host 0.0.0.0 --port 7862
directory=/app/ai-web-vuln-sim/backend
user=root
priority=30
environment=PYTHONPATH="/app/ai-web-vuln-sim/backend/app"
autostart=true
autorestart=true
startsecs=3
startretries=3
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0